"""A digest built mid-session must say so, and must not become a baseline.

THE DEFECT (found 2026-08-31). `python -m zebra digest` at 13:00 reads a
half-day log and a half-day store and renders exactly like an end-of-day one.
"Cycles 45 (09:15-12:55)" reads as a SHORT day, not as a partial read; the
cohort running-net reads as the day's answer.

The part that outlives the moment: `write()` persists it to
`logs/eod/<date>.json`, which is tomorrow's `prev` baseline. Every warning that
first appears in the AFTERNOON is then mis-flagged "NEW today" the next day --
a false alarm generated by yesterday's reporting rather than by anything that
happened.

Both halves are fixed: the digest carries `partial` and renders a banner, and
a partial `prev` is refused as a baseline (the "NEW today" flag simply does not
fire, which is the honest degradation).

Run:  cd Helper && PURE_PYTHON=1 python -m pytest zebra/tests/test_digest_partial_day.py -v
"""
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pytest

HELPER = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(HELPER))

from zebra import config as cfg                                  # noqa: E402
from zebra import digest                                         # noqa: E402


class _Now:
    """A pinned IST clock. `feedback_pin_the_wall_clock_in_tests`: without it
    these pass or fail depending on when the suite happens to run."""

    def __init__(self, dt):
        self.dt = dt

    def __call__(self, tz=None):
        return self.dt


def _at(y, m, d, hh, mm):
    return datetime(y, m, d, hh, mm, tzinfo=cfg.IST)


@pytest.fixture
def clock(monkeypatch):
    def _set(dt):
        monkeypatch.setattr(digest, 'datetime',
                            type('D', (), {
                                'now': staticmethod(lambda tz=None: dt),
                                'strptime': staticmethod(datetime.strptime),
                            }))
        return dt
    return _set


# ── is it partial? ─────────────────────────────────────────────────────────

def test_a_weekday_run_before_the_close_is_partial(clock):
    now = clock(_at(2026, 9, 1, 13, 0))          # Tuesday, market open
    assert digest._is_partial(now.strftime('%Y-%m-%d')) is True


def test_a_run_after_the_close_is_not_partial(clock):
    now = clock(_at(2026, 9, 1, 16, 5))
    assert digest._is_partial(now.strftime('%Y-%m-%d')) is False


def test_the_boundary_is_the_configured_close(clock):
    """15:30 exactly is the close, not before it."""
    now = clock(_at(2026, 9, 1, 15, 30))
    assert digest._is_partial(now.strftime('%Y-%m-%d')) is False
    now = clock(_at(2026, 9, 1, 15, 29))
    assert digest._is_partial(now.strftime('%Y-%m-%d')) is True


def test_a_PAST_day_is_never_partial(clock):
    """Re-rendering last Tuesday at noon describes a finished session."""
    clock(_at(2026, 9, 1, 13, 0))
    assert digest._is_partial('2026-08-25') is False


def test_a_weekend_run_is_not_partial(clock):
    """Nothing is still to come on a Saturday."""
    now = clock(_at(2026, 9, 5, 11, 0))          # Saturday
    assert now.weekday() == 5
    assert digest._is_partial(now.strftime('%Y-%m-%d')) is False


# ── it has to SAY so ───────────────────────────────────────────────────────

def _real_digest(tmp_path, monkeypatch, day='2026-09-01'):
    """A digest dict of the REAL shape, from an empty log/store directory.

    Hand-building one is how the first cut of this file failed: `render` reads
    a dozen nested keys, so a literal is a test of the literal.
    """
    monkeypatch.setattr(cfg, 'LOG_DIR', tmp_path)
    return digest.build(day)


def test_the_banner_is_rendered_at_the_top(tmp_path, monkeypatch):
    d = _real_digest(tmp_path, monkeypatch)
    d['partial'] = True
    text = digest.render(d)
    head = text.splitlines()[:5]
    assert any('PARTIAL' in l for l in head), text[:400]
    assert any('still open' in l for l in head)


def test_a_complete_digest_carries_no_banner(tmp_path, monkeypatch):
    """The negative control -- a banner on every digest is one nobody reads."""
    d = _real_digest(tmp_path, monkeypatch)
    d['partial'] = False
    assert 'PARTIAL' not in digest.render(d)


def test_an_old_digest_without_the_key_still_renders(tmp_path, monkeypatch):
    """`render` must tolerate a dict written before this field existed."""
    d = _real_digest(tmp_path, monkeypatch)
    d.pop('partial', None)
    assert 'PARTIAL' not in digest.render(d)


# ── and it must not become tomorrow's baseline ─────────────────────────────

def test_a_partial_baseline_is_refused(tmp_path, monkeypatch):
    """THE DURABLE HALF. Differencing against a half-day marks every
    afternoon warning as NEW the next morning."""
    import json
    monkeypatch.setattr(cfg, 'LOG_DIR', tmp_path)
    eod = tmp_path / 'eod'
    eod.mkdir()
    (eod / '2026-08-31.json').write_text(json.dumps(
        {'date': '2026-08-31', 'partial': True,
         'warnings': {'a stale quote': 1}}), encoding='utf-8')

    d = digest.build('2026-09-01')

    assert not any(f.startswith('NEW today') for f in d['flags']), (
        'a half-day digest was used as a baseline')


def test_a_COMPLETE_baseline_is_still_used(tmp_path, monkeypatch):
    """The negative control: refusing partial baselines must not disable the
    comparison altogether."""
    import json
    monkeypatch.setattr(cfg, 'LOG_DIR', tmp_path)
    eod = tmp_path / 'eod'
    eod.mkdir()
    (eod / '2026-08-31.json').write_text(json.dumps(
        {'date': '2026-08-31', 'partial': False, 'warnings': {}}),
        encoding='utf-8')

    # `build` reads the real store/log through cfg.LOG_DIR (now tmp), so both
    # are empty; what is asserted is only that `prev` survived the filter.
    d = digest.build('2026-09-01')
    assert d['date'] == '2026-09-01'
    assert 'partial' in d, 'the flag is not carried on the built dict'
