"""
NEO Trade Terminal - Order Tracker

Tracks all orders placed by this application with unique identifiers.
Prevents confusion between different order types (SL vs EXIT vs ENTRY).

Key Features:
1. Unique order tags for each order type
2. Tracks pending orders and their expected types
3. Verifies orders by tag, not just by criteria
4. Thread-safe for concurrent access
"""

import threading
import time
import logging
from typing import Dict, Optional, Any, List
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class OrderType(Enum):
    """Order types with unique prefixes for tags."""
    ENTRY = "ENT"       # New position entry
    EXIT = "EXT"        # Position exit (full or partial)
    SL = "SLP"          # Stop loss order
    SL_RECREATE = "SLR" # Stop loss recreated after modification
    TARGET = "TGT"      # Target order
    MODIFY = "MOD"      # Modified order


@dataclass
class TrackedOrder:
    """Represents a tracked order."""
    tag: str                        # Unique tag we generated
    symbol: str
    transaction_type: str           # B or S
    quantity: int
    order_type: str                 # MKT, L, SL, SL-L
    price_type: OrderType           # Our classification
    placed_at: float                # Unix timestamp
    order_id: Optional[str] = None  # Filled after confirmation
    status: str = "pending"         # pending, confirmed, failed, cancelled
    api_response: Optional[Dict] = None


class OrderTracker:
    """
    Tracks all orders placed by this application.

    Usage:
        tracker = OrderTracker()

        # Before placing order
        tag = tracker.generate_tag(OrderType.EXIT, symbol)

        # Place order with tag
        response = client.place_order(..., tag=tag)

        # Register the order
        tracker.register_order(tag, symbol, txn_type, qty, order_type, OrderType.EXIT)

        # After getting response
        if response.get('nOrdNo'):
            tracker.confirm_order(tag, response['nOrdNo'])
        else:
            # Verify by tag in order book
            order_id = tracker.verify_order_by_tag(client, tag)
    """

    def __init__(self):
        self._orders: Dict[str, TrackedOrder] = {}  # tag -> TrackedOrder
        self._order_id_to_tag: Dict[str, str] = {}  # order_id -> tag (reverse lookup)
        self._lock = threading.Lock()
        self._counter = 0  # For unique tag generation

    def generate_tag(self, order_type: OrderType, symbol: str = "") -> str:
        """
        Generate a unique tag for an order.

        Format: {TYPE}_{TIMESTAMP}_{COUNTER}
        Example: EXT_1706543210_001

        Args:
            order_type: Type of order (ENTRY, EXIT, SL, etc.)
            symbol: Trading symbol (optional, for logging)

        Returns:
            Unique tag string (max 20 chars for NEO API compatibility)
        """
        with self._lock:
            self._counter += 1
            # Use milliseconds for uniqueness, but truncate for tag length limit
            timestamp = int(time.time() * 1000) % 10000000000  # Last 10 digits
            tag = f"{order_type.value}_{timestamp}_{self._counter:03d}"

            # NEO API tag limit is typically 20 chars
            if len(tag) > 20:
                tag = tag[:20]

            logger.debug(f"[TRACKER] Generated tag: {tag} for {order_type.name} {symbol}")
            return tag

    def register_order(self, tag: str, symbol: str, transaction_type: str,
                       quantity: int, api_order_type: str,
                       price_type: OrderType) -> TrackedOrder:
        """
        Register a new order that we're about to place.

        Call this BEFORE placing the order to track it.

        Args:
            tag: Unique tag generated by generate_tag()
            symbol: Trading symbol
            transaction_type: B or S
            quantity: Order quantity
            api_order_type: MKT, L, SL, SL-L
            price_type: Our classification (EXIT, SL, etc.)

        Returns:
            TrackedOrder object
        """
        with self._lock:
            order = TrackedOrder(
                tag=tag,
                symbol=symbol,
                transaction_type=transaction_type,
                quantity=quantity,
                order_type=api_order_type,
                price_type=price_type,
                placed_at=time.time()
            )
            self._orders[tag] = order
            logger.info(f"[TRACKER] Registered: {tag} {symbol} {transaction_type} "
                       f"qty={quantity} type={api_order_type} ({price_type.name})")
            return order

    def confirm_order(self, tag: str, order_id: str,
                      response: Optional[Dict] = None) -> bool:
        """
        Confirm an order was placed successfully.

        Call this after receiving order_id from API.

        Args:
            tag: Order tag
            order_id: Order ID from API
            response: Full API response (optional)

        Returns:
            True if order was found and confirmed
        """
        with self._lock:
            if tag not in self._orders:
                logger.warning(f"[TRACKER] Confirm failed - tag not found: {tag}")
                return False

            order = self._orders[tag]
            order.order_id = order_id
            order.status = "confirmed"
            order.api_response = response

            # Create reverse lookup
            self._order_id_to_tag[order_id] = tag

            logger.info(f"[TRACKER] Confirmed: {tag} -> {order_id}")
            return True

    def mark_failed(self, tag: str, reason: str = "") -> bool:
        """Mark an order as failed."""
        with self._lock:
            if tag not in self._orders:
                return False
            self._orders[tag].status = "failed"
            logger.warning(f"[TRACKER] Failed: {tag} - {reason}")
            return True

    def get_order_by_tag(self, tag: str) -> Optional[TrackedOrder]:
        """Get order by tag."""
        with self._lock:
            return self._orders.get(tag)

    def get_order_by_id(self, order_id: str) -> Optional[TrackedOrder]:
        """Get order by order_id."""
        with self._lock:
            tag = self._order_id_to_tag.get(order_id)
            if tag:
                return self._orders.get(tag)
            return None

    def get_tag_for_order_id(self, order_id: str) -> Optional[str]:
        """Get tag for an order_id."""
        with self._lock:
            return self._order_id_to_tag.get(order_id)

    def is_our_order(self, order_id: str) -> bool:
        """Check if an order_id belongs to us."""
        with self._lock:
            return order_id in self._order_id_to_tag

    def get_order_type(self, order_id: str) -> Optional[OrderType]:
        """Get the type of order (EXIT, SL, etc.) by order_id."""
        order = self.get_order_by_id(order_id)
        if order:
            return order.price_type
        return None

    def verify_order_by_tag(self, client, tag: str,
                            max_age_seconds: int = 15) -> Optional[str]:
        """
        Verify an order exists in order book by searching for our tag.

        This is the SAFE way to verify orders - by unique tag, not criteria.

        Args:
            client: NEO API client
            tag: Order tag to search for
            max_age_seconds: How old the order can be

        Returns:
            Order ID if found, None otherwise
        """
        order = self.get_order_by_tag(tag)
        if not order:
            logger.warning(f"[TRACKER] Verify failed - tag not registered: {tag}")
            return None

        try:
            order_report = client.order_report()
            orders = order_report.get('data', []) if order_report else []

            for api_order in orders:
                # Check if this order has our tag
                order_tag = api_order.get('remarks', api_order.get('tag', ''))

                if order_tag == tag:
                    order_id = api_order.get('nOrdNo', api_order.get('orderId', ''))
                    status = api_order.get('ordSt', '').lower()

                    if order_id and status not in ['rejected', 'cancelled']:
                        logger.info(f"[TRACKER] Verified by tag: {tag} -> {order_id} (status: {status})")

                        # Update our records
                        self.confirm_order(tag, order_id)
                        return order_id

            # Tag not found - also check by criteria as fallback
            # but ONLY if criteria match exactly
            current_time = time.time()
            for api_order in orders:
                # Match ALL criteria strictly
                if (api_order.get('trdSym') == order.symbol and
                    api_order.get('trnsTp') == order.transaction_type and
                    int(api_order.get('qty', 0) or 0) == order.quantity):

                    # Check order type matches
                    api_type = api_order.get('prcTp', '').upper()
                    expected_type = order.order_type.upper()

                    # MKT should only match MKT
                    if expected_type == 'MKT' and api_type not in ['MKT', 'MARKET']:
                        continue
                    # SL should only match SL
                    if expected_type in ['SL', 'SL-L', 'SL-M'] and api_type not in ['SL', 'SL-L', 'SL-M']:
                        continue

                    # Check age
                    order_time_str = api_order.get('ordDtTm', '')
                    if order_time_str:
                        try:
                            order_dt = datetime.strptime(order_time_str, "%d-%b-%Y %H:%M:%S")
                            age = current_time - order_dt.timestamp()
                            if age > max_age_seconds:
                                continue
                        except (ValueError, TypeError):
                            pass

                    # Check status
                    status = api_order.get('ordSt', '').lower()
                    if status in ['rejected', 'cancelled']:
                        continue
                    if expected_type == 'MKT' and status == 'trigger pending':
                        continue  # MKT can't be trigger pending

                    order_id = api_order.get('nOrdNo', '')
                    if order_id:
                        logger.info(f"[TRACKER] Verified by criteria (tag not found): {tag} -> {order_id}")
                        self.confirm_order(tag, order_id)
                        return order_id

            logger.warning(f"[TRACKER] Order not found in book: {tag}")
            return None

        except Exception as e:
            logger.error(f"[TRACKER] Verify error: {e}")
            return None

    def cleanup_old_orders(self, max_age_hours: int = 24):
        """Remove orders older than max_age_hours."""
        with self._lock:
            cutoff = time.time() - (max_age_hours * 3600)
            old_tags = [
                tag for tag, order in self._orders.items()
                if order.placed_at < cutoff
            ]
            for tag in old_tags:
                order = self._orders.pop(tag, None)
                if order and order.order_id:
                    self._order_id_to_tag.pop(order.order_id, None)

            if old_tags:
                logger.info(f"[TRACKER] Cleaned up {len(old_tags)} old orders")

    def get_pending_orders(self, symbol: Optional[str] = None) -> List[TrackedOrder]:
        """Get all pending (unconfirmed) orders."""
        with self._lock:
            orders = [o for o in self._orders.values() if o.status == "pending"]
            if symbol:
                orders = [o for o in orders if o.symbol == symbol]
            return orders

    def get_stats(self) -> Dict[str, Any]:
        """Get tracker statistics."""
        with self._lock:
            total = len(self._orders)
            confirmed = sum(1 for o in self._orders.values() if o.status == "confirmed")
            failed = sum(1 for o in self._orders.values() if o.status == "failed")
            pending = sum(1 for o in self._orders.values() if o.status == "pending")

            by_type = {}
            for o in self._orders.values():
                t = o.price_type.name
                by_type[t] = by_type.get(t, 0) + 1

            return {
                'total': total,
                'confirmed': confirmed,
                'failed': failed,
                'pending': pending,
                'by_type': by_type
            }


# Singleton instance for global access
_tracker_instance: Optional[OrderTracker] = None
_tracker_lock = threading.Lock()


def get_order_tracker() -> OrderTracker:
    """Get or create the global OrderTracker instance."""
    global _tracker_instance
    with _tracker_lock:
        if _tracker_instance is None:
            _tracker_instance = OrderTracker()
        return _tracker_instance
