"""
Kite API Adapter - Uses official Kite Connect API with shared token from SNAIL

This adapter reads the access token generated by SNAIL bot at 8:45 AM daily
and uses the official kiteconnect library for all API operations.

Benefits over enctoken:
- Official API (more stable, no web scraping)
- No credentials needed in CROCODILE (SNAIL handles auth)
- Better error messages and documentation
- Rate limiting handled by library
"""

import json
import os
import time
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional

import pandas as pd
from loguru import logger

from src.api.broker_adapter import BrokerAdapter
from src.core.api_resilience import critical_api_call, standard_api_call
from src.utils.timezone_helper import now_ist, today_ist, IST

# Try to import kiteconnect
try:
    from kiteconnect import KiteConnect
    KITECONNECT_AVAILABLE = True
except ImportError:
    KITECONNECT_AVAILABLE = False
    logger.warning("kiteconnect library not installed. Run: pip install kiteconnect")


class KiteAPIAdapter(BrokerAdapter):
    """
    Kite API adapter using official kiteconnect library

    Reads access token from shared file created by SNAIL bot.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize Kite API adapter

        Args:
            config: Configuration dictionary (already loaded)
        """
        if not KITECONNECT_AVAILABLE:
            raise ImportError(
                "kiteconnect library required for Kite API mode. "
                "Install with: pip install kiteconnect"
            )

        self.config = config
        self._kite: Optional[KiteConnect] = None
        self._api_key: Optional[str] = None
        self._user_id: Optional[str] = None
        self._order_tag = config.get('kite', {}).get('order_tag', 'croc')
        self._rate_limit_delay = config.get('kite', {}).get('rate_limit_delay', 1.0)

        # Token file path (from SNAIL)
        kite_api_config = config.get('kite', {}).get('kite_api', {})
        self._token_file = kite_api_config.get('token_file', '../data/kite_access_token.json')
        self._validate_token_date = kite_api_config.get('validate_token_date', True)

        # Resolve relative path
        if not os.path.isabs(self._token_file):
            project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            self._token_file = os.path.normpath(os.path.join(project_root, self._token_file))

        # Data cache
        self._cache = {}
        self._instruments_cache = {}
        self.instruments_file = config.get('instruments', {}).get('cache_file', 'data/instruments.csv')

        # Resolve instruments file path
        if not os.path.isabs(self.instruments_file):
            project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            self.instruments_file = os.path.normpath(os.path.join(project_root, self.instruments_file))

        logger.info(f"KiteAPIAdapter initialized (token file: {self._token_file})")

    def _load_token(self) -> Dict[str, Any]:
        """
        Load access token from shared JSON file

        Returns:
            Dict with access_token, api_key, user_id, generated_at

        Raises:
            FileNotFoundError: If token file doesn't exist
            ValueError: If token is expired or invalid
        """
        if not os.path.exists(self._token_file):
            raise FileNotFoundError(
                f"Kite API token file not found: {self._token_file}\n"
                "Ensure SNAIL bot has run morning startup to generate token."
            )

        with open(self._token_file, 'r') as f:
            token_data = json.load(f)

        # Validate token date if enabled
        if self._validate_token_date:
            generated_at = token_data.get('generated_at', '')
            if generated_at:
                try:
                    # Parse ISO format datetime
                    token_time = datetime.fromisoformat(generated_at.replace('Z', '+00:00'))

                    # Make timezone-aware if not already
                    if token_time.tzinfo is None:
                        token_time = token_time.replace(tzinfo=IST)

                    current_time = now_ist()

                    # Token is valid if generated today OR yesterday after 6 AM and before today 6 AM
                    today_6am = current_time.replace(hour=6, minute=0, second=0, microsecond=0)

                    if current_time < today_6am:
                        # Before 6 AM today - token from yesterday is valid
                        valid_from = (today_6am - timedelta(days=1))
                    else:
                        # After 6 AM today - token must be from today
                        valid_from = today_6am

                    if token_time < valid_from:
                        raise ValueError(
                            f"Kite API token expired. Generated at {generated_at}, "
                            f"but must be generated after {valid_from.isoformat()}. "
                            "Ensure SNAIL morning startup has run today."
                        )

                    logger.debug(f"Token validated: generated at {generated_at}")

                except (ValueError, TypeError) as e:
                    if "Kite API token expired" in str(e):
                        raise
                    logger.warning(f"Could not validate token date: {e}")

        return token_data

    def _get_kite(self) -> KiteConnect:
        """
        Get authenticated KiteConnect instance

        Returns:
            Authenticated KiteConnect instance
        """
        if self._kite is None:
            token_data = self._load_token()

            self._api_key = token_data.get('api_key')
            self._user_id = token_data.get('user_id')
            access_token = token_data.get('access_token')

            if not all([self._api_key, access_token]):
                raise ValueError(
                    "Invalid token file format. Expected: api_key, access_token"
                )

            self._kite = KiteConnect(api_key=self._api_key)
            self._kite.set_access_token(access_token)

            logger.info(f"KiteConnect initialized for user: {self._user_id}")

        return self._kite

    def _rate_limit(self):
        """Apply rate limiting before API calls"""
        time.sleep(self._rate_limit_delay)

    # =========================================================================
    # CONNECTION & VALIDATION
    # =========================================================================

    def validate_connection(self) -> bool:
        """Validate API connection and token"""
        try:
            kite = self._get_kite()
            profile = kite.profile()
            logger.info(f"Connection validated for user: {profile.get('user_id')}")
            return True
        except Exception as e:
            logger.error(f"Connection validation failed: {e}")
            return False

    # =========================================================================
    # HISTORICAL DATA
    # =========================================================================

    @standard_api_call("Get Historical Data")
    def get_historical_data(
        self,
        instrument_token: str,
        start_date: str,
        end_date: str,
        interval: str = 'day'
    ) -> pd.DataFrame:
        """Fetch historical OHLC data"""
        cache_key = f"{instrument_token}_{start_date}_{end_date}_{interval}"

        # Check cache
        cache_expiry = self.config.get('supertrend', {}).get('cache_expiry_minutes', 60)
        if cache_key in self._cache:
            cache_time, cached_data = self._cache[cache_key]
            if now_ist() - cache_time < timedelta(minutes=cache_expiry):
                logger.debug(f"Using cached data for {instrument_token}")
                return cached_data

        self._rate_limit()
        kite = self._get_kite()

        # Map interval names (Kite API uses different format)
        interval_map = {
            'day': 'day',
            'minute': 'minute',
            '3minute': '3minute',
            '5minute': '5minute',
            '10minute': '10minute',
            '15minute': '15minute',
            '30minute': '30minute',
            '60minute': '60minute',
        }
        kite_interval = interval_map.get(interval, interval)

        data = kite.historical_data(
            instrument_token=int(instrument_token),
            from_date=start_date,
            to_date=end_date,
            interval=kite_interval,
            oi=True
        )

        if not data:
            logger.warning(f"No data found for {instrument_token} from {start_date} to {end_date}")
            return pd.DataFrame()

        # Convert to DataFrame
        df = pd.DataFrame(data)

        # Rename columns to match expected format
        df = df.rename(columns={
            'date': 'Date',
            'open': 'Open',
            'high': 'High',
            'low': 'Low',
            'close': 'Close',
            'volume': 'Volume'
        })

        # Keep only required columns
        df = df[['Date', 'Open', 'High', 'Low', 'Close', 'Volume']]

        # Cache result
        self._cache[cache_key] = (now_ist(), df.copy())

        logger.info(f"Fetched {len(df)} candles for instrument {instrument_token}")
        return df

    def get_historical_data_sampled(
        self,
        instrument_token: str,
        timeframe: str,
        years_back: float
    ) -> pd.DataFrame:
        """Fetch daily data and resample to monthly/weekly timeframes"""
        try:
            end_date = now_ist().date()
            start_date = end_date - timedelta(days=int(years_back * 365))

            logger.info(f"Fetching {timeframe} data for {instrument_token} from {start_date} to {end_date}")

            # Collect daily data year by year
            daily_data_list = []
            for year in range(start_date.year, end_date.year + 1):
                year_start = datetime(year, 1, 1).date()
                year_end = datetime(year, 12, 31).date()

                if year_start < start_date:
                    year_start = start_date
                if year_end > end_date:
                    year_end = end_date

                try:
                    year_df = self.get_historical_data(
                        instrument_token=instrument_token,
                        start_date=year_start.strftime('%Y-%m-%d'),
                        end_date=year_end.strftime('%Y-%m-%d'),
                        interval='day'
                    )
                    if not year_df.empty:
                        daily_data_list.append(year_df)
                except Exception as e:
                    logger.warning(f"Failed to fetch data for year {year}: {e}")
                    continue

                time.sleep(0.1)

            if not daily_data_list:
                return pd.DataFrame()

            daily_df = pd.concat(daily_data_list, ignore_index=True)
            daily_df['Date'] = pd.to_datetime(daily_df['Date'])
            daily_df.set_index('Date', inplace=True)
            daily_df = daily_df[~daily_df.index.duplicated(keep='first')]
            daily_df.sort_index(inplace=True)

            if timeframe == 'daily':
                daily_df.reset_index(inplace=True)
                return daily_df

            # Resample
            resample_freq = 'M' if timeframe == 'monthly' else 'W'
            resampled_df = daily_df.resample(resample_freq).agg({
                'Open': 'first',
                'High': 'max',
                'Low': 'min',
                'Close': 'last',
                'Volume': 'sum'
            })
            resampled_df.dropna(inplace=True)
            resampled_df.reset_index(inplace=True)

            logger.info(f"Resampled {len(daily_df)} daily to {len(resampled_df)} {timeframe} candles")
            return resampled_df

        except Exception as e:
            logger.error(f"Failed to fetch sampled historical data: {e}")
            raise

    @standard_api_call("Get Instrument LTP")
    def get_instrument_ltp(self, instrument_token: str) -> float:
        """Get Last Traded Price for an instrument"""
        self._rate_limit()
        kite = self._get_kite()

        # Try to get LTP using quote
        try:
            # Format: exchange:tradingsymbol or just instrument_token
            quotes = kite.ltp([f"NSE:{instrument_token}"])
            if quotes:
                key = list(quotes.keys())[0]
                ltp = quotes[key].get('last_price')
                if ltp and ltp > 0:
                    return float(ltp)
        except Exception:
            pass

        # Fallback: Get from historical data
        today = now_ist().strftime('%Y-%m-%d')
        df = self.get_historical_data(instrument_token, today, today, 'minute')

        if df is None or df.empty:
            end_date = now_ist().strftime('%Y-%m-%d')
            start_date = (now_ist() - timedelta(days=7)).strftime('%Y-%m-%d')
            df = self.get_historical_data(instrument_token, start_date, end_date, 'day')

            if df is None or df.empty:
                raise Exception(f"No LTP data available for instrument {instrument_token}")

        ltp = float(df['Close'].iloc[-1])

        if ltp <= 0:
            raise Exception(f"Invalid LTP for instrument {instrument_token}: {ltp}")

        return ltp

    # =========================================================================
    # ORDER OPERATIONS
    # =========================================================================

    @standard_api_call("Place Order")
    def place_order(
        self,
        tradingsymbol: str,
        exchange: str,
        transaction_type: str,
        quantity: int,
        order_type: str,
        price: Optional[float] = None,
        product: str = "CNC",
        validity: str = "DAY",
        tag: Optional[str] = None
    ) -> Dict[str, Any]:
        """Place order on Zerodha"""
        self._rate_limit()
        kite = self._get_kite()

        order_params = {
            'exchange': exchange,
            'tradingsymbol': tradingsymbol,
            'transaction_type': transaction_type,
            'quantity': quantity,
            'order_type': order_type,
            'product': product,
            'validity': validity,
        }

        if order_type == "LIMIT" and price:
            order_params['price'] = price

        if tag:
            order_params['tag'] = tag
        elif self._order_tag:
            order_params['tag'] = self._order_tag

        order_id = kite.place_order(variety='regular', **order_params)

        logger.info(
            f"Order placed: {transaction_type} {quantity} {tradingsymbol} @ "
            f"{price if price else 'MARKET'} - Order ID: {order_id}"
        )

        return {'order_id': order_id}

    @critical_api_call("Cancel Regular Order")
    def cancel_order(self, order_id: str, variety: str = "regular", verify: bool = True) -> bool:
        """Cancel a regular order"""
        self._rate_limit()
        kite = self._get_kite()

        kite.cancel_order(variety=variety, order_id=order_id)
        logger.info(f"Cancel request sent for order: {order_id}")

        if verify:
            time.sleep(1)
            try:
                order_status = self.get_order_status(order_id)
                actual_status = order_status.get('status', '')

                if actual_status == 'CANCELLED':
                    logger.info(f"Order cancellation verified: {order_id}")
                    return True
                elif actual_status in ['COMPLETE', 'REJECTED']:
                    logger.warning(f"Order {order_id} cannot be cancelled - status is {actual_status}")
                    return False
                else:
                    raise Exception(f"Order cancellation failed. Order {order_id} still {actual_status}")
            except Exception as e:
                if "cancellation failed" in str(e):
                    raise
                logger.warning(f"Could not verify cancellation for {order_id}: {e}")
                return True

        return True

    @standard_api_call("Get Order Status")
    def get_order_status(self, order_id: str) -> Dict[str, Any]:
        """Get status of a specific order"""
        self._rate_limit()
        kite = self._get_kite()

        order_history = kite.order_history(order_id=order_id)

        if not order_history:
            raise Exception(f"No order history found for order_id: {order_id}")

        latest_order = order_history[-1]

        logger.debug(
            f"Order {order_id} status: {latest_order.get('status')}, "
            f"filled: {latest_order.get('filled_quantity', 0)}/{latest_order.get('quantity', 0)}"
        )

        return latest_order

    def get_all_orders(self) -> List[Dict[str, Any]]:
        """Get all orders placed today"""
        try:
            self._rate_limit()
            kite = self._get_kite()
            all_orders = kite.orders()
            logger.info(f"Fetched {len(all_orders)} orders from Zerodha")
            return all_orders
        except Exception as e:
            logger.error(f"Failed to fetch all orders: {e}")
            raise

    def get_bot_orders(self, tag: Optional[str] = None) -> List[Dict[str, Any]]:
        """Get orders placed by this bot (filtered by tag)"""
        try:
            if tag is None:
                tag = self._order_tag

            all_orders = self.get_all_orders()
            bot_orders = [order for order in all_orders if order.get('tag') == tag]

            logger.info(f"Found {len(bot_orders)} bot orders (tag='{tag}')")
            return bot_orders
        except Exception as e:
            logger.error(f"Failed to fetch bot orders: {e}")
            raise

    # =========================================================================
    # GTT OPERATIONS
    # =========================================================================

    @critical_api_call("Place GTT Order")
    def place_gtt_order(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Place GTT order"""
        self._rate_limit()
        kite = self._get_kite()

        # Extract from payload (matching existing format)
        condition = payload['condition']
        orders = payload['orders']
        gtt_type = payload['type']
        expires_at = payload['expires_at']

        trigger_id = kite.place_gtt(
            trigger_type=gtt_type,
            tradingsymbol=condition['tradingsymbol'],
            exchange=condition['exchange'],
            trigger_values=condition['trigger_values'],
            last_price=condition['last_price'],
            orders=[{
                'transaction_type': orders[0]['transaction_type'],
                'quantity': orders[0]['quantity'],
                'order_type': 'LIMIT',
                'product': orders[0]['product'],
                'price': orders[0]['price'],
            }]
        )

        logger.info(f"GTT placed: {trigger_id}")
        return {'trigger_id': trigger_id}

    @critical_api_call("Cancel GTT Order")
    def cancel_gtt_order(self, gtt_id: str) -> bool:
        """Cancel GTT order"""
        self._rate_limit()
        kite = self._get_kite()

        kite.delete_gtt(trigger_id=int(gtt_id))
        logger.info(f"GTT cancelled: {gtt_id}")
        return True

    @standard_api_call("Get GTT Orders")
    def get_gtt_orders(self) -> List[Dict[str, Any]]:
        """Get all active GTT orders"""
        self._rate_limit()
        kite = self._get_kite()
        gtt_orders = kite.get_gtts()
        return gtt_orders or []

    # =========================================================================
    # PORTFOLIO & MARGIN
    # =========================================================================

    @standard_api_call("Get Positions")
    def get_positions(self) -> Dict[str, List[Dict[str, Any]]]:
        """Get current positions"""
        self._rate_limit()
        kite = self._get_kite()
        return kite.positions()

    @standard_api_call("Get Margins")
    def get_margins(self) -> Dict[str, Any]:
        """Fetch margin data"""
        self._rate_limit()
        kite = self._get_kite()
        margins = kite.margins()

        # Wrap in 'data' to match enctoken adapter format
        return {'data': margins}

    # =========================================================================
    # INSTRUMENTS
    # =========================================================================

    def get_instrument_token(self, script: str) -> str:
        """Get instrument token for a given script symbol"""
        if not self._instruments_cache:
            if not self.load_instruments_cache():
                if not self.fetch_instruments_data():
                    raise ValueError("Unable to load instruments data")

        variations = self._generate_symbol_variations(script)

        token = None
        matched_symbol = None

        for variation in variations:
            token = self._instruments_cache.get(variation)
            if token:
                matched_symbol = variation
                break

        if not token:
            logger.warning(f"Token not found for {script}, refreshing cache")
            if self.fetch_instruments_data():
                for variation in variations:
                    token = self._instruments_cache.get(variation)
                    if token:
                        matched_symbol = variation
                        break

            if not token:
                raise ValueError(f"Instrument token not found for: {script}")

        if matched_symbol != script.upper():
            logger.info(f"Symbol mapping: {script} -> {matched_symbol}")

        return token

    def _generate_symbol_variations(self, script: str) -> List[str]:
        """Generate possible symbol variations"""
        script_upper = script.upper()
        variations = [script_upper]

        if '&' in script_upper:
            variations.append(script_upper.replace('&', '-'))
            variations.append(script_upper.replace('&', ''))

        if '-' in script_upper:
            variations.append(script_upper.replace('-', ''))

        return list(dict.fromkeys(variations))

    def fetch_instruments_data(self) -> bool:
        """Fetch instruments data from API"""
        try:
            logger.info("Fetching instruments data from Kite API")
            self._rate_limit()
            kite = self._get_kite()

            instruments = kite.instruments("NSE")

            # Filter to EQ only
            eq_instruments = [
                {
                    'instrument_token': str(i['instrument_token']),
                    'tradingsymbol': i['tradingsymbol'],
                    'name': i.get('name', ''),
                    'exchange': i['exchange'],
                    'instrument_type': i.get('instrument_type', '')
                }
                for i in instruments
                if i.get('instrument_type') == 'EQ'
            ]

            if not eq_instruments:
                return False

            # Save to file
            os.makedirs(os.path.dirname(self.instruments_file), exist_ok=True)
            df = pd.DataFrame(eq_instruments)
            df.to_csv(self.instruments_file, index=False)

            # Build cache
            self._instruments_cache = {
                row['tradingsymbol']: row['instrument_token']
                for row in eq_instruments
            }

            logger.info(f"Fetched {len(eq_instruments)} instruments")
            return True

        except Exception as e:
            logger.error(f"Failed to fetch instruments: {e}")
            return False

    def load_instruments_cache(self) -> bool:
        """Load instruments from local cache"""
        try:
            if not os.path.exists(self.instruments_file):
                logger.warning(f"Instruments file not found: {self.instruments_file}")
                return self.fetch_instruments_data()

            # Check file age
            file_mtime = os.path.getmtime(self.instruments_file)
            file_time_ist = datetime.fromtimestamp(file_mtime, tz=IST)
            current_time_ist = now_ist()
            file_age = current_time_ist - file_time_ist
            max_age_hours = self.config.get('instruments', {}).get('max_age_hours', 24)

            if file_age.total_seconds() > max_age_hours * 3600:
                logger.warning(f"Instruments file is {file_age.total_seconds()/3600:.1f}h old, refreshing")
                return self.fetch_instruments_data()

            df = pd.read_csv(self.instruments_file)

            if df.empty:
                return self.fetch_instruments_data()

            required_columns = {'tradingsymbol', 'instrument_token'}
            if not required_columns.issubset(set(df.columns)):
                return self.fetch_instruments_data()

            self._instruments_cache = {
                str(row['tradingsymbol']): str(row['instrument_token'])
                for _, row in df.iterrows()
                if pd.notna(row['tradingsymbol']) and pd.notna(row['instrument_token'])
            }

            logger.info(f"Loaded {len(self._instruments_cache)} instruments from cache")
            return True

        except Exception as e:
            logger.error(f"Error loading instruments cache: {e}")
            return self.fetch_instruments_data()

    # =========================================================================
    # CACHE MANAGEMENT
    # =========================================================================

    def clear_cache(self) -> None:
        """Clear the data cache"""
        self._cache.clear()
        logger.info("Cache cleared")

    def clear_instruments_cache(self) -> None:
        """Clear the instruments cache"""
        self._instruments_cache.clear()
        logger.info("Instruments cache cleared")

    # =========================================================================
    # PROPERTIES
    # =========================================================================

    @property
    def order_tag(self) -> str:
        """Get the order tag"""
        return self._order_tag

    @property
    def trade_method(self) -> str:
        """Get the trade method"""
        return "kite_api"
